### ISSUE TITLE
Question about Image / Video Tags?

### ISSUE THREAD

**Issue by alr2413** [ARCANEDEV/LaravelSitemap#27]
Hi,

Thanks for providing this package. I have a question about how we can add Image/Video tags to the generated sitemap?

Thanks

**Comment by arcanedev-maroc** [comment]
I haven’t tried to add images or videos but i believe you can achieve it by adding custom `attributes` because `Arcanedev\LaravelSitemap\Entities\Url` extends the ` Illuminate\Support\Fluent`.

And of course, you need to edit the `xml` in the views folder to render the image/video tags.
